---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ include "openstack-ck8s-cluster.clusterName" . }}
  labels:
    {{ include "openstack-ck8s-cluster.labels" . | nindent 4 }}
    ccmOpenStackChart: enabled
    csiCinderChart: enabled
    {{- if .Values.addons.kubernetesDashboard.enabled }}
    kubernetesDashboardChart: enabled
    {{- end }}
spec:
  clusterNetwork: {{ .Values.clusterNetwork | toYaml | nindent 4 }}
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: CK8sControlPlane
    name: {{ include "openstack-ck8s-cluster.componentName" (list . "control-plane") }}
    namespace: {{ .Release.Namespace }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: OpenStackCluster
    name: {{ include "openstack-ck8s-cluster.clusterName" . }}
    namespace: {{ .Release.Namespace }}
