{{- if not .Values.cloudCredentialsSecretName }}
{{- if .Values.clouds }}
{{- $cloud := index .Values.clouds .Values.cloudName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openstack-ck8s-cluster.cloudCredentialsSecretName" . }}
  labels: {{ include "openstack-ck8s-cluster.componentLabels" (list . "cloud-credentials") | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
stringData:
  clouds.yaml: |
    clouds:
      {{ printf "%s:" .Values.cloudName }}
        {{ index .Values.clouds .Values.cloudName | toYaml | indent 8 | trim }}
  {{- with .Values.cloudCACert }}
  cacert: |
    {{ . | indent 4 | trim }}
  {{- end }}
{{- else }}
{{- fail "clouds must be specified if cloudCredentialsSecretName is not given" }}
{{- end }}
{{- end }}
