{{/*
  Create new machine template on spec changes as machine templates are immutable.
*/}}
{{- define "openstack-ck8s-cluster.controlplane.machinetemplate.spec" -}}
template:
  spec:
    identityRef:
      name: {{ include "openstack-ck8s-cluster.cloudCredentialsSecretName" . }}
      cloudName: {{ .Values.cloudName }}
    flavor: {{ .Values.controlPlane.machineFlavor | required ".Values.controlPlane.machineFlavor is required" }}
    {{- with .Values.machineSSHKeyName }}
    sshKeyName: {{ . }}
    {{- end }}
    image:
      {{- if .Values.machineImageId }}
      id: {{ .Values.machineImageId }}
      {{- else }}
      {{- fail "machineImageId is required" }}
      {{- end }}
{{- end }}

{{- define "openstack-ck8s-cluster.controlplane.machinetemplate.checksum" -}}
{{- include "openstack-ck8s-cluster.controlplane.machinetemplate.spec" . | sha256sum }}
{{- end }}

{{- define "openstack-ck8s-cluster.controlplane.machinetemplate.name" -}}
{{- $checksum := include "openstack-ck8s-cluster.controlplane.machinetemplate.checksum" . }}
{{- include "openstack-ck8s-cluster.componentName" (list . "control-plane") }}-{{ trunc 8 $checksum }}
{{- end }}

apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: {{ include "openstack-ck8s-cluster.controlplane.machinetemplate.name" . }}
  labels: {{ include "openstack-ck8s-cluster.componentLabels" (list . "control-plane") | nindent 4 }}
  annotations:
    {{ .Values.projectPrefix }}/template-checksum: {{ include "openstack-ck8s-cluster.controlplane.machinetemplate.checksum" . }}
    helm.sh/resource-policy: keep
spec:
  {{- include "openstack-ck8s-cluster.controlplane.machinetemplate.spec" . | nindent 2 }}
